baseURL = "https://www.skyclops.pictures/"
languageCode = "en-us"
title = "Skyclops Pictures - Premiere Aerial Video"
theme = "hugo-creative-theme"
disableKinds = ["taxonomy","taxonomyTerm", "RSS"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Skyclops Pictures"
	description = "Skyclops Pictures provides premiere aerial video to clients of all sizes. Using drones, Skyclops Pictures is able to elevate your next project. All pilots are FAA certified."

	# The path must be relative to the static folder
	favicon = "favicon.png"
	faviconSVG = "favicon.svg"


	# Navigation
	[params.navigation]
		brand = "Skyclops.Pictures"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Skyclops Pictures"
		subtitle   = "Premiere Aerial Video and Cinematography"
		buttonText = "Book Now"


	# About section
	[params.about]
		headline    = "FAA Certified Pilots"
		description = "Don't hire a pilot that is not licensed! Skyclops Pictures pilots are professionally licensed and can legally operate drones for compensation. A professional pilot will ensure a safe operation for everyone involved."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-video-camera"
            title = "High Quality Video"
            description = "I have an eye for Cinematography, meaning shots are carefully crafted for maximum impact. This is my art!"

        [[params.services.list]]
			icon = "fa-plane"
			title = "Aerial Mapping"
			description = "I fly more than just quadcopters. Using my custom-built fixed wing autonomous drone, I can fly longer missions for search and rescue and aerial mapping!"

		[[params.services.list]]
            icon = "fa-wifi"
            title = "Licensed by the FCC"
            description = "I use powerful radios. That means we can fly farther and get the shot you need!"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Diamond Guarantee"
            description = "I am so confident that you will be satisfied with the result that I will refund your order if the video does not meet your expectations!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "I am also available for your livestreaming needs"

		[params.aside.button]
			#text = "Find out more"
			#link = "https://brandonkalinowski.com"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Looking to see how Skyclops Pictures can elevate your next project? Drop me a line and I will get back to you as soon as possible! I look forward to hearing from you!"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		headline = "Skyclops Pictures - Premiere Aerial Video"
		copyright = "All Content Copyright 2018 Brandon Kalinowski"
